name: pawnco
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  dio: ^5.9.0
  google_fonts: ^6.3.2
  logger: ^2.6.2
  cached_network_image: ^3.4.1
  easy_debounce: ^2.0.3
  flutter_native_splash: ^2.4.6
  intl: ^0.20.2
  mockito: ^5.5.1
  build_runner: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter_native_splash:
  color: "#ffffff"
  image: assets/splash.png
  color_dark: "#121212"
  image_dark: assets/splash.png
  android: true
  ios: true
  web: false
  android_12:
    color: "#ffffff"
    image: assets/splash.png
    color_dark: "#121212"
    image_dark: assets/splash.png


flutter:


  uses-material-design: true

  assets:
    - assets/