// Mocks generated by Mockito 5.4.6 from annotations
// in pawnco/test/domain/use_cases/delete_pet_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:pawnco/app/domain/entities/order.dart' as _i3;
import 'package:pawnco/app/domain/entities/pets.dart' as _i2;
import 'package:pawnco/app/domain/repositories/pets_repository.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePets_0 extends _i1.SmartFake implements _i2.Pets {
  _FakePets_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOrder_1 extends _i1.SmartFake implements _i3.Order {
  _FakeOrder_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PetRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPetRepository extends _i1.Mock implements _i4.PetRepository {
  @override
  _i5.Future<List<_i2.Pets>> getPets() =>
      (super.noSuchMethod(
            Invocation.method(#getPets, []),
            returnValue: _i5.Future<List<_i2.Pets>>.value(<_i2.Pets>[]),
            returnValueForMissingStub: _i5.Future<List<_i2.Pets>>.value(
              <_i2.Pets>[],
            ),
          )
          as _i5.Future<List<_i2.Pets>>);

  @override
  _i5.Future<_i2.Pets> getPetDetail(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getPetDetail, [id]),
            returnValue: _i5.Future<_i2.Pets>.value(
              _FakePets_0(this, Invocation.method(#getPetDetail, [id])),
            ),
            returnValueForMissingStub: _i5.Future<_i2.Pets>.value(
              _FakePets_0(this, Invocation.method(#getPetDetail, [id])),
            ),
          )
          as _i5.Future<_i2.Pets>);

  @override
  _i5.Future<_i2.Pets> addPet(Map<String, dynamic>? json) =>
      (super.noSuchMethod(
            Invocation.method(#addPet, [json]),
            returnValue: _i5.Future<_i2.Pets>.value(
              _FakePets_0(this, Invocation.method(#addPet, [json])),
            ),
            returnValueForMissingStub: _i5.Future<_i2.Pets>.value(
              _FakePets_0(this, Invocation.method(#addPet, [json])),
            ),
          )
          as _i5.Future<_i2.Pets>);

  @override
  _i5.Future<_i2.Pets> editPet(Map<String, dynamic>? json) =>
      (super.noSuchMethod(
            Invocation.method(#editPet, [json]),
            returnValue: _i5.Future<_i2.Pets>.value(
              _FakePets_0(this, Invocation.method(#editPet, [json])),
            ),
            returnValueForMissingStub: _i5.Future<_i2.Pets>.value(
              _FakePets_0(this, Invocation.method(#editPet, [json])),
            ),
          )
          as _i5.Future<_i2.Pets>);

  @override
  _i5.Future<dynamic> deletePet(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deletePet, [id]),
            returnValue: _i5.Future<dynamic>.value(),
            returnValueForMissingStub: _i5.Future<dynamic>.value(),
          )
          as _i5.Future<dynamic>);

  @override
  _i5.Future<List<_i2.Pets>> getPetsByTag(List<String>? tags) =>
      (super.noSuchMethod(
            Invocation.method(#getPetsByTag, [tags]),
            returnValue: _i5.Future<List<_i2.Pets>>.value(<_i2.Pets>[]),
            returnValueForMissingStub: _i5.Future<List<_i2.Pets>>.value(
              <_i2.Pets>[],
            ),
          )
          as _i5.Future<List<_i2.Pets>>);

  @override
  _i5.Future<_i3.Order> postPetOrder(Map<String, dynamic>? json) =>
      (super.noSuchMethod(
            Invocation.method(#postPetOrder, [json]),
            returnValue: _i5.Future<_i3.Order>.value(
              _FakeOrder_1(this, Invocation.method(#postPetOrder, [json])),
            ),
            returnValueForMissingStub: _i5.Future<_i3.Order>.value(
              _FakeOrder_1(this, Invocation.method(#postPetOrder, [json])),
            ),
          )
          as _i5.Future<_i3.Order>);
}
