// Mocks generated by Mockito 5.4.6 from annotations
// in pawnco/test/presentation/controllers/pet_info/pet_info_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:pawnco/app/domain/entities/category.dart' as _i8;
import 'package:pawnco/app/domain/entities/pets.dart' as _i3;
import 'package:pawnco/app/domain/entities/tags.dart' as _i9;
import 'package:pawnco/app/domain/repositories/pets_repository.dart' as _i2;
import 'package:pawnco/app/domain/usecases/add_pet_usecase.dart' as _i6;
import 'package:pawnco/app/domain/usecases/edit_pet_usecase.dart' as _i7;
import 'package:pawnco/app/domain/usecases/get_pet_detail_usecase.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePetRepository_0 extends _i1.SmartFake implements _i2.PetRepository {
  _FakePetRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePets_1 extends _i1.SmartFake implements _i3.Pets {
  _FakePets_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetPetDetailUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetPetDetailUsecase extends _i1.Mock
    implements _i4.GetPetDetailUsecase {
  @override
  _i2.PetRepository get repo =>
      (super.noSuchMethod(
            Invocation.getter(#repo),
            returnValue: _FakePetRepository_0(this, Invocation.getter(#repo)),
            returnValueForMissingStub: _FakePetRepository_0(
              this,
              Invocation.getter(#repo),
            ),
          )
          as _i2.PetRepository);

  @override
  _i5.Future<_i3.Pets> call(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#call, [id]),
            returnValue: _i5.Future<_i3.Pets>.value(
              _FakePets_1(this, Invocation.method(#call, [id])),
            ),
            returnValueForMissingStub: _i5.Future<_i3.Pets>.value(
              _FakePets_1(this, Invocation.method(#call, [id])),
            ),
          )
          as _i5.Future<_i3.Pets>);
}

/// A class which mocks [AddPetUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddPetUsecase extends _i1.Mock implements _i6.AddPetUsecase {
  @override
  _i2.PetRepository get repo =>
      (super.noSuchMethod(
            Invocation.getter(#repo),
            returnValue: _FakePetRepository_0(this, Invocation.getter(#repo)),
            returnValueForMissingStub: _FakePetRepository_0(
              this,
              Invocation.getter(#repo),
            ),
          )
          as _i2.PetRepository);

  @override
  _i5.Future<_i3.Pets> call(Map<String, dynamic>? json) =>
      (super.noSuchMethod(
            Invocation.method(#call, [json]),
            returnValue: _i5.Future<_i3.Pets>.value(
              _FakePets_1(this, Invocation.method(#call, [json])),
            ),
            returnValueForMissingStub: _i5.Future<_i3.Pets>.value(
              _FakePets_1(this, Invocation.method(#call, [json])),
            ),
          )
          as _i5.Future<_i3.Pets>);
}

/// A class which mocks [EditPetUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockEditPetUsecase extends _i1.Mock implements _i7.EditPetUsecase {
  @override
  _i2.PetRepository get repo =>
      (super.noSuchMethod(
            Invocation.getter(#repo),
            returnValue: _FakePetRepository_0(this, Invocation.getter(#repo)),
            returnValueForMissingStub: _FakePetRepository_0(
              this,
              Invocation.getter(#repo),
            ),
          )
          as _i2.PetRepository);

  @override
  _i5.Future<_i3.Pets> call(Map<String, dynamic>? json) =>
      (super.noSuchMethod(
            Invocation.method(#call, [json]),
            returnValue: _i5.Future<_i3.Pets>.value(
              _FakePets_1(this, Invocation.method(#call, [json])),
            ),
            returnValueForMissingStub: _i5.Future<_i3.Pets>.value(
              _FakePets_1(this, Invocation.method(#call, [json])),
            ),
          )
          as _i5.Future<_i3.Pets>);
}

/// A class which mocks [Pets].
///
/// See the documentation for Mockito's code generation for more information.
class MockPets extends _i1.Mock implements _i3.Pets {}

/// A class which mocks [Category].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategory extends _i1.Mock implements _i8.Category {}

/// A class which mocks [Tags].
///
/// See the documentation for Mockito's code generation for more information.
class MockTags extends _i1.Mock implements _i9.Tags {}
