// Mocks generated by Mockito 5.4.6 from annotations
// in pawnco/test/presentation/controllers/home/home_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:pawnco/app/domain/entities/pets.dart' as _i5;
import 'package:pawnco/app/domain/repositories/pets_repository.dart' as _i2;
import 'package:pawnco/app/domain/usecases/delete_pet_usecase.dart' as _i6;
import 'package:pawnco/app/domain/usecases/get_pets_usecase.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePetRepository_0 extends _i1.SmartFake implements _i2.PetRepository {
  _FakePetRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetPetsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetPetsUseCase extends _i1.Mock implements _i3.GetPetsUseCase {
  @override
  _i2.PetRepository get repo =>
      (super.noSuchMethod(
            Invocation.getter(#repo),
            returnValue: _FakePetRepository_0(this, Invocation.getter(#repo)),
            returnValueForMissingStub: _FakePetRepository_0(
              this,
              Invocation.getter(#repo),
            ),
          )
          as _i2.PetRepository);

  @override
  _i4.Future<List<_i5.Pets>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i4.Future<List<_i5.Pets>>.value(<_i5.Pets>[]),
            returnValueForMissingStub: _i4.Future<List<_i5.Pets>>.value(
              <_i5.Pets>[],
            ),
          )
          as _i4.Future<List<_i5.Pets>>);
}

/// A class which mocks [DeletePetUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeletePetUsecase extends _i1.Mock implements _i6.DeletePetUsecase {
  @override
  _i2.PetRepository get repo =>
      (super.noSuchMethod(
            Invocation.getter(#repo),
            returnValue: _FakePetRepository_0(this, Invocation.getter(#repo)),
            returnValueForMissingStub: _FakePetRepository_0(
              this,
              Invocation.getter(#repo),
            ),
          )
          as _i2.PetRepository);

  @override
  _i4.Future<dynamic> call(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#call, [id]),
            returnValue: _i4.Future<dynamic>.value(),
            returnValueForMissingStub: _i4.Future<dynamic>.value(),
          )
          as _i4.Future<dynamic>);
}

/// A class which mocks [Pets].
///
/// See the documentation for Mockito's code generation for more information.
class MockPets extends _i1.Mock implements _i5.Pets {}
