// Mocks generated by Mockito 5.4.6 from annotations
// in pawnco/test/presentation/controllers/order/order_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:pawnco/app/domain/entities/order.dart' as _i3;
import 'package:pawnco/app/domain/entities/pets.dart' as _i6;
import 'package:pawnco/app/domain/repositories/pets_repository.dart' as _i2;
import 'package:pawnco/app/domain/usecases/order_pet_usecase.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePetRepository_0 extends _i1.SmartFake implements _i2.PetRepository {
  _FakePetRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOrder_1 extends _i1.SmartFake implements _i3.Order {
  _FakeOrder_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [OrderPetUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockOrderPetUseCase extends _i1.Mock implements _i4.OrderPetUseCase {
  @override
  _i2.PetRepository get repo =>
      (super.noSuchMethod(
            Invocation.getter(#repo),
            returnValue: _FakePetRepository_0(this, Invocation.getter(#repo)),
            returnValueForMissingStub: _FakePetRepository_0(
              this,
              Invocation.getter(#repo),
            ),
          )
          as _i2.PetRepository);

  @override
  _i5.Future<_i3.Order> call(Map<String, dynamic>? json) =>
      (super.noSuchMethod(
            Invocation.method(#call, [json]),
            returnValue: _i5.Future<_i3.Order>.value(
              _FakeOrder_1(this, Invocation.method(#call, [json])),
            ),
            returnValueForMissingStub: _i5.Future<_i3.Order>.value(
              _FakeOrder_1(this, Invocation.method(#call, [json])),
            ),
          )
          as _i5.Future<_i3.Order>);
}

/// A class which mocks [Pets].
///
/// See the documentation for Mockito's code generation for more information.
class MockPets extends _i1.Mock implements _i6.Pets {}

/// A class which mocks [Order].
///
/// See the documentation for Mockito's code generation for more information.
class MockOrder extends _i1.Mock implements _i3.Order {}
